dbswitch:
  source:
    type: MYSQL
    url: jdbc:mysql://172.17.2.10:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&tinyInt1isBit=false&rewriteBatchedStatements=true&useCompression=true
    driver-class-name: 'com.mysql.jdbc.Driver'
    driver-path: D:\Workspace\IdeaProjects\dbswitch\drivers\mysql\mysql-5
    username: 'test'
    password: '123456'
    fetch-size: 10000
    source-schema: 'test'
    table-type: 'TABLE'
    source-includes: ''
    source-excludes: ''
    incr-table-columns:
      t_test_table: id
    regex-table-mapper:
      - from-pattern: '^'
        to-value: 'T_'
    regex-column-mapper:

  target:
    type: POSTGRESQL
    url: jdbc:postgresql://172.17.2.10:5432/test
    driver-class-name: org.postgresql.Driver
    driver-path: D:\Workspace\IdeaProjects\dbswitch\drivers\postgresql\postgresql-11.4
    username: 'postgres'
    password: '123456'
    target-schema: public
    table-name-case: UPPER
    column-name-case: UPPER
    target-drop: true
    create-table-auto-increment: false
    writer-engine-insert: false
    change-data-sync: true
    target-sync-option: INSERT_UPDATE_DELETE
