spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/dbswitch_db;MODE=MySQL;CASE_INSENSITIVE_IDENTIFIERS=TRUE;DATABASE_TO_UPPER=FALSE;DATABASE_TO_LOWER=FALSE
    username: root
    password: 123456
    validation-query: SELECT 1
    test-on-borrow: true
  flyway:
    locations: classpath:db/h2
    baseline-on-migrate: true
    table: DBSWITCH_SCHEMA_HISTORY
    enabled: true
