spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.31.57:5432/dbswitch?currentSchema=public
    username: postgres
    password: 123456
    validation-query: SELECT 1
    test-on-borrow: true
  flyway:
    locations: classpath:db/postgres
    baseline-on-migrate: true
    table: dbswitch_schema_history
    enabled: true
