spring:
  profiles:
    include: h2
    #include: mysql
    #include: postgres
  application:
    name: dbswitch-admin
  tomcat:
    uri-encoding: UTF-8
    max-http-header-size: 8096
  mvc:
    throw-exception-if-no-handler-found: false
    static-path-pattern: /statics/**

server:
  port: 9088

mybatis:
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    map-underscore-to-camel-case: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

dbswitch:
  configuration:
    drivers-base-path: ${APP_DRIVERS_PATH}
